name: moonraker
author: arksine@github.com
homepage: https://moonraker.readthedocs.io/en/latest/
license: GNU GPL v3.0
data-source:
  git: https://github.com/Arksine/moonraker.git
provides:
  system-packages:
    apt: [ python3-dev, libopenjp2-7, python3-libgpiod, curl, libcurl4-openssl-dev, libssl-dev, liblmdb-dev, libsodium-dev, zlib1g-dev, libjpeg-dev, packagekit, wireless-tools ]
  pip-app:
    services:
      - !PKG moonraker.service
    pip-requirements: scripts/moonraker-requirements.txt
  system-config:
    blueprint:
      - [ !PKG apiserver.conf, /etc/nginx/server.d/proxy/apiserver.conf ]
      - [ !PKG upstream-apiserver.conf, /etc/nginx/conf.d/upstream-apiserver.conf ]
  moonraker-config:
    link:
      - source: !PKG notifier/telegram.conf
        target: moonraker.telegram.conf
        only:
          notifier-telegram: true
    template:
      - source: !PKG loader.conf
        target: true
        only:
          loader: true
      - source: !PKG base.conf
        target: true
        unless:
          loader: true
      - source: !PKG moonraker.conf
        target: moonraker.conf
        only:
          loader: true
        unless:
          user_config: false
triggers:
  installed:
    - shell: scripts/set-policykit-rules.sh --disable-systemctl
      quiet: true
  updated:
    - message: |
        moonraker.secrets:
        
        [printer]
        name: Cetus/Ender/Prusa/Voron/...
        
        [telegram]
        token: ...
        chat: ...
        
        
        To get chat id type something to bo and run:
        curl https://api.telegram.org/bot<TOKEN>/getUpdates
      only:
        notifier-telegram: true
