name: rpi-uart
author: noone@nowhere.com
license: WTF
provides:
  ansible: !PKG playbook.yml
triggers:
  updated:
    - message: |
        klipper mcu config:
        
        [mcu]
        serial: /dev/ttyAMA0
        restart_method: command