name: mainsail
author: mainsail-crew@github.com
license: GNU GPL v3.0
type: service
data-source:
  zip: https://github.com/mainsail-crew/mainsail/releases/latest/download/mainsail.zip
provides:
- system-config:
    template:
      - [ !PKG mainsail.conf, /etc/nginx/server.d/content/mainsail.conf ]
triggers:
  installed:
    - service-reload: nginx
  updated:
    - service-reload: nginx
  always:
    - shell: !PKG update-icons.sh
