name: canboot
author: Arksine@github.com
license: GNU GPL v3.0
homepage: https://github.com/Arksine/CanBoot
data-source:
  git: https://github.com/Arksine/CanBoot
provides: {}
triggers:
  installed:
    - shell: !PKG link.sh