name: katapult
author: Arksine@github.com
license: GNU GPL v3.0
homepage: https://github.com/Arksine/katapult
data-source:
  git: https://github.com/Arksine/katapult
provides:
  system-packages:
    apt: [ dfu-util ]
triggers:
  installed:
    - shell: !PKG link.sh